dist: trusty
install:
- git clone https://github.com/akerl/brew.git ~/.brew
- git clone ../homebrew-core ~/.brew/Library/Taps/halyard/homebrew-core
- chmod g-w ~/.brew/Library/Taps/halyard/homebrew-core/Formula/*
script:
- "~/.brew/bin/brew audit --except=revision_and_version_scheme ~/.brew/Library/Taps/halyard/homebrew-core/Formula/*"
notifications:
  email: false
  slack:
    secure: fFDYMkgARuxFdnB3KdsouqYhBjEKPp339wTtDjHsuoS8FAKwIqeQyZYak3uvIBFaSUvIE788eBzXO2dRkZ1+UXjLqECfKqmAfb5R7taSqrXGQdi7ryUoiIYuGQpkDyQTaCSZspwDNgpmnAUexGt8RSfZhpnXAu0oLS3dLabqN202UOAS64NnRi+wUwiuVCkLeaFMEnSgD0NWAUIjrMxylDqp2fhp5Q8BHWtYY3kjg+JYeg87SsgOBtY3QZqvrfweeYbIuswW3yYpYoHANzIQQ5lzk9ic318XNCwmSNj4gd/YSQfndMnlSBJ9Z3r+ewwaH6Pnukd1LKOhYPY2OPnMJ2+aXFVU+ohudhJpJ1Wi2KwT9X/7KmKy/b/OIKYu0wfWWnOvvej0SyechR1D2j7wzFOI0rkpoAAZME1b0F3NTYcgyt6X57z54qhFJz3j7wSARDAO8Sn2sp1w1RTnNn/LcNnRKSrQQapM50fgP9MZ97v9tNSM05iwoHXgz85wPSNOwuzcInCojPOqAKIGZwWTlVRXOmpio8MhQjP6y5KbW7abjsR3VlCc+GZcA2GgdHI1OmQHStRpAz+m9t7+O2rP1Li875LZ7T1PVHx4dM0UENw/ojoAQ1iSYraZwYxF/BzhKO1HDs+1kvxO4jtPmKunXUyVcx3fZukJPPnzeBJArFU=
